import SinglePost from "@/components/Post/SinglePost";
import Tag from "@/components/Tag/Tag";
import { getAllPosts, getAllTags, getPostForTopPage } from "@/lib/notionAPI";
import Head from "next/head";
import Link from "next/link";

export const getStaticProps = async () => {
  // const allPosts = await getAllPosts(); //全件取得
  const fourPosts = await getPostForTopPage(4);
  const allTags = await getAllTags();

  return {
    props: {
      fourPosts: fourPosts,
      allTags: allTags
    },
    revalidate: 60,
  }
}

export default function Home({ fourPosts, allTags }: any) {
  //console.log(fourPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico"/>
      </Head>
      <main className="container w-full">
        <Tag tags={allTags}/>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {fourPosts.map((post: any) => (
            <div className="mx-4" key={post.id}>
              <SinglePost
                imege={post.imege}
                title={post.title}
                description={post.description}
                date={post.date}
                slug={post.slug}
                tags={post.tags}
                isPagenationPage={false}
              />
            </div>
          ))}
        </section>
        <div className="mb-6 mx-auto rounded-md px-5 block text-center">
          <Link href="posts/page/1" className="text-center text-orange-600 duration-300 hover:text-orange-300 cursor-pointer">
            ..もっと見る
          </Link>
        </div>
      </main>
    </div>
  );
}
